name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: setup JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 11
          distribution: adopt
        
      - name: build backend
        run: sh build.sh backend
        
      - name: save backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: artifacts/backend.jar
        
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
                    
      - name: build frontend      
        run: sh build.sh frontend
        
      - name: save frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: artifacts/frontend

  
  docker_deploy:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: list files
      run: |
        apt update
        apt install tree
        tree -halt

    - name: Build and push Docker images
      run: |
        docker image build --build-arg backend=./artifacts/backend/backend.jar --build-arg frontend=./artifacts/frontend/frontend  -t ${{ secrets.DOCKERHUB_USERNAME }}/mmorpg:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/mmorpg:$(date +%s) .
        docker image push ${{ secrets.DOCKERHUB_USERNAME }}/mmorpg
