name: CI

on:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: copy ssh key
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.PRIVATE_SSH_KEY }} > ~/id_rsa
          echo ${{ secrets.PUBLIC_SSH_KEY }} > ~/id_rsa.pub
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ${{ secrets.SSH_COMMAND }}
          
        
#      mkdir -p ~/.ssh
#    steps:
#    - uses: garygrossgarten/github-action-ssh@release
#      with:
#        command: ${{ secrets.SSH_COMMAND }}
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USER }}
#        privateKey: ${{ secrets.SSH_KEY }}
