name: deploy ssh

on:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: copy ssh keys
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_PUBLIC_KEY }} > ~/id_rsa.pub

      - name: upgrade
        run: |
          - name: executing remote ssh commands using password
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              script: ${{ secrets.SSH_COMMAND }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
